### ISSUE TITLE
panic: interface conversion: interface is nil, not string

### ISSUE THREAD

**Issue by VitaliyPetroff** [karolgorecki/goprove#15]
## Passed tests: 8 of 11

panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x24dcc0, 0xc420446040)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.printOutput(0xc4202edbc0, 0x8, 0x8, 0xc4202e4ea0, 0x3, 0x4)
    /Users/petroff/golang/src/github.com/karolgorecki/goprove/cmd/goprove/main.go:81 +0x353
main.main()
    /Users/petroff/golang/src/github.com/karolgorecki/goprove/cmd/goprove/main.go:64 +0x116

Is it normal? May be I do something wrong?
I just tried to run it on my project.

**Comment by karolgorecki** [comment]
It should work. You should pass to `goprove` a directory. So you can go to you repo folder and just run `goprove .`. If this doesn't work, please let me know how do you call the goprove. Thanks!

**Comment by karolgorecki** [comment]
Ok issue fixed

**Comment by VitaliyPetroff** [comment]
No works fine. Thx
